apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: estate-rental
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS userdb;
    CREATE DATABASE IF NOT EXISTS propertydb;
    CREATE DATABASE IF NOT EXISTS rental_agreement_db;
    CREATE DATABASE IF NOT EXISTS notifications;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: estate-rental
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mysql-root-password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-init
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-init
        configMap:
          name: mysql-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: estate-rental
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
