apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: estate-rental
spec:
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "9000"
    spec:
      containers:
        - name: auth-server
          image: yassinekamouss/authorization-service:latest
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-service:8888" 
            - name: USER_URI
              value: "user-management-service:8081" 
            - name: JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_SERVER_URL
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
  namespace: estate-rental
  labels: 
    app: auth-server
spec:
  ports:
    - name: http
      port: 9000
      targetPort: 9000
  selector:
    app: auth-server
