apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: estate-rental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8085"
    spec:
      containers:
        - name: notification-service
          image: yassinekamouss/notification-estate-rental-service:latest
          ports:
            - containerPort: 8085
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JAVA_TOOL_OPTIONS
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-service:8888"
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CONFIG_SERVER_URL
            - name: PROD_DB_NOTIFICATION_URL
              value: "jdbc:mysql://mysql:3306/notifications?useSSL=false&allowPublicKeyRetrieval=true"
            - name: PROD_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USERNAME
            - name: PROD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP_SERVERS
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: estate-rental
  labels: 
    app: notification-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8085
      targetPort: 8085
  selector:
    app: notification-service