apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-app
  namespace: estate-rental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-app
  template:
    metadata:
      labels:
        app: public-app
    spec:
      containers:
        - name: public-app
          image: yassinekamouss/public-app:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: public-app-service
  namespace: estate-rental
spec:
  type: ClusterIP
  selector:
    app: public-app
  ports:
    - name: http
      protocol: TCP
      port: 4200
      targetPort: 80
