apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-service
  namespace: estate-rental
spec:
  selector:
    matchLabels:
      app: user-management-service
  template:
    metadata:
      labels:
        app: user-management-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: user-management-service
          image: yassinekamouss/user-management-service:latest
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CONFIG_SERVER_URL
            - name: PROD_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PROD_DB_URL
            - name: PROD_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USERNAME
            - name: PROD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-password
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JAVA_TOOL_OPTIONS
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  namespace: estate-rental
  labels: 
    app: user-management-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
  selector:
    app: user-management-service
