apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: estate-rental
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper:latest
        ports:
        - containerPort: 2181
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: estate-rental
spec:
  ports:
  - port: 2181
    targetPort: 2181
  selector:
    app: zookeeper
